adb:
  device_serial: emulator-5554
  ip: 127.0.0.1
bot:
  auto_start_game: true
  enable_gui: false
  load_deck: true
  log_level: WARNING
ingame:
  play_action: 0.3
visuals:
  save_images: false
  save_labels: false
  show_images: false
